---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ['Ubuntu','Debian']

  - name: install apache2 package
    apt:
      name: apache2
    when: ansible_distribution in ['Ubuntu','Debian']

  - name: add php support to apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ['Ubuntu','Debian']

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution in ['CentOS']

  - name: install apache2 package
    dnf:
      name: httpd
    when: ansible_distribution in ['CentOS']

  - name: add php support to apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution in ['CentOS']

